cities/urls.py
from django.conf.urls import url
from cities.views import CityCreateView, CityListView, CityDetailView

urlpatterns = [
    url(r'^$', CityListView.as_view(), name="list"),
    url(r'^(?P<pk>\d+)/$', CityDetailView.as_view(), name="detail"),
    url(r'^create/$', CityCreateView.as_view(), name="create"),
]

project/urls.py
from django.conf import settings
from django.conf.urls import url, include
from django.contrib import admin
from django.conf.urls.static import static
from django.core.urlresolvers import reverse_lazy
from django.views.generic import RedirectView


urlpatterns = [
    url(r'^$', RedirectView.as_view(url=reverse_lazy('cities:list'))),
    url(r'^admin/', admin.site.urls),
    url(r'^cities/', include('cities.urls', namespace='cities')),
] + static(settings.STATIC_URL, document_root=settings.STATIC_ROOT)

cities/models.py
from __future__ import unicode_literals

from django.contrib.gis.db import models
from django.contrib.gis.geos import Point

POINT = Point(-104.9903, 39.7392, srid=4326)


class City(models.Model):
    name = models.CharField(max_length=255)
    coordinates = models.PointField(help_text="To generate the map for your location")
    city_hall = models.PointField(blank=True, null=True)

    def __unicode__(self):
        return self.name

    @property
    def latitude(self):
        return self.coordinates.y

    @property
    def longitude(self):
        return self.coordinates.x


class District(models.Model):
    city = models.ForeignKey(City)
    name = models.CharField(max_length=255)
    location = models.PointField(help_text="To generate the map for your location")

    def __unicode__(self):
        return self.name

maps/models.py
from django.db import models
from django_google_maps import fields as map_fields


class Rental(models.Model):
    address = map_fields.AddressField(max_length=200)
    geolocation = map_fields.GeoLocationField(max_length=100, blank=True)

cities/forms.py
from django import forms

from cities.models import City
from mapwidgets.widgets import GooglePointFieldWidget, GoogleStaticMapWidget, GoogleStaticOverlayMapWidget


class CityCreateForm(forms.ModelForm):

    class Meta:
        model = City
        fields = ("name", "coordinates", "city_hall")
        widgets = {
            'coordinates': GooglePointFieldWidget,
            'city_hall': GooglePointFieldWidget,
        }


class CityDetailForm(forms.ModelForm):

    class Meta:
        model = City
        fields = ("name", "coordinates", "city_hall")
        widgets = {
            'coordinates': GoogleStaticMapWidget(zoom=12, size="240x240"),
            'city_hall': GoogleStaticOverlayMapWidget(zoom=12, thumbnail_size="50x50", size="640x640"),
        }

cities/views.py
from django.db.models import Avg, FloatField, ExpressionWrapper, Func
from django.core.urlresolvers import reverse_lazy
from django.views.generic import FormView, ListView, UpdateView

from cities.forms import CityCreateForm, CityDetailForm
from cities.models import City


class CityListView(ListView):
    queryset = City.objects.all()
    template_name = "cities/list.html"
    context_object_name = "cities"

    def get_context_data(self, **kwargs):
        context = super().get_context_data(**kwargs)
        context['avg_lat'] = City.objects.all().annotate(
            lat=ExpressionWrapper(
                Func(
                    'coordinates',
                    function='ST_Y'
                ),
                output_field=FloatField()
            )
        ).annotate(
            long=ExpressionWrapper(
                Func(
                    'coordinates',
                    function='ST_X'
                ),
                output_field=FloatField()
            )
        ).order_by('lat')

        context['avg_long'] = City.objects.all().annotate(
            long=ExpressionWrapper(
                Func(
                    'coordinates',
                    function='ST_X'
                ),
                output_field=FloatField()
            )
        ).order_by('long')

        print([(obj.lat, obj.long) for obj in context['avg_lat']])
        context['center'] = context['avg_lat'].aggregate(avg_long=Avg('long'), avg_lat=Avg('lat'))
        return context


class CityDetailView(UpdateView):
    form_class = CityDetailForm
    model = City
    template_name = "cities/detail.html"


class CityCreateView(FormView):
    template_name = "cities/form.html"
    form_class = CityCreateForm
    success_url = reverse_lazy("cities:list")

    def form_valid(self, form):
        form.save()
        return super(CityCreateView, self).form_valid(form)

maps/views.py
from django.shortcuts import render

# Create your views here.

cities/templates/base.html
{% load staticfiles %}
<!DOCTYPE html>
<html lang="en">

<head>
    <meta charset="utf-8">
    <meta http-equiv="X-UA-Compatible" content="IE=edge">
    <meta name="viewport" content="width=device-width, initial-scale=1">
    <!-- The above 3 meta tags *must* come first in the head; any other head content must come *after* these tags -->
    <title>Geolocater 2</title>

    <!-- Bootstrap -->
    <link rel="stylesheet" href="https://maxcdn.bootstrapcdn.com/bootstrap/3.3.7/css/bootstrap.min.css" integrity="sha384-BVYiiSIFeK1dGmJRAkycuHAHRg32OmUcww7on3RYdg4Va+PmSTsz/K68vbdEjh4u" crossorigin="anonymous">

    <!-- Optional theme -->
    <link rel="stylesheet" href="https://maxcdn.bootstrapcdn.com/bootstrap/3.3.7/css/bootstrap-theme.min.css" integrity="sha384-rHyoN1iRsVXV4nD0JutlnGaslCJuC7uwjduW9SVrLvRYooPp2bWYgmgJQIXwl/Sp" crossorigin="anonymous">
    <script src="https://ajax.googleapis.com/ajax/libs/jquery/1.12.4/jquery.min.js"></script>
    <!-- Include all compiled plugins (below), or include individual files as needed -->
    <!-- Latest compiled and minified CSS -->
    <!-- Latest compiled and minified JavaScript -->
    <script src="https://maxcdn.bootstrapcdn.com/bootstrap/3.3.7/js/bootstrap.min.js" integrity="sha384-Tc5IQib027qvyjSMfHjOMaLkfuWVxZxUPnCJA7l2mCWNIpG9mGCD8wGNIcPD7Txa" crossorigin="anonymous"></script>

    <style>
        .gmap {
            height: 700px;
            width: 100%;
        }
    </style>

    {% block extrahead %} 

    {% endblock extrahead %} 
    <!-- HTML5 shim and Respond.js for IE8 support of HTML5 elements and media queries -->
    <!-- WARNING: Respond.js doesn't work if you view the page via file:// -->
    <!--[if lt IE 9]>
      <script src="https://oss.maxcdn.com/html5shiv/3.7.3/html5shiv.min.js"></script>
      <script src="https://oss.maxcdn.com/respond/1.4.2/respond.min.js"></script>
    <![endif]-->
</head>

<body>
    <div class="container help-block">
        {% block content %}

        {% endblock content %}
    </div>
    {#  Script, which adds map  #}
    {% block script %}
    {% endblock script %}
    

</body>

</html>

cities/templates/cities/detail.html
{% extends "base.html" %} 
{% block extrahead %} 
    {{ form.media }} 
{% endblock extrahead %} 
{% block content %} 
    {{ form.as_p }} 
{% endblock content %}

cities/templates/cities/form.html
{% extends "base.html" %} 
{% block extrahead %} 
{{ form.media }}

<script type="text/javascript">
    $(document).on("google_point_map_widget:marker_create", function(e, lat, lng, locationInputElem, mapWrapID) {
        console.log(locationInputElem); // django widget textarea widget (hidden)
        console.log(lat, lng); // created marker coordinates
        console.log(mapWrapID); // map widget wrapper element ID
    });
    $(document).on("google_point_map_widget:marker_change", function(e, lat, lng, locationInputElem, mapWrapID) {
        console.log(locationInputElem); // django widget textarea widget (hidden)
        console.log(lat, lng); // changed marker coordinates
        console.log(mapWrapID); // map widget wrapper element ID
    });
    $(document).on("google_point_map_widget:marker_delete", function(e, lat, lng, locationInputElem, mapWrapID) {
        console.log(locationInputElem); // django widget textarea widget (hidden)
        console.log(lat, lng); // deleted marker coordinates
        console.log(mapWrapID); // map widget wrapper element ID
    })
</script>
{% endblock extrahead %} 
{% block content %}
<form action="{% url 'cities:create' %}" method="post">
    {% csrf_token %} {{ form.as_p }}
    <button type="submit" class="btn btn-primary">Create</button>
</form>
{% endblock content %}

cities/templates/cities/list.html
{% extends "base.html" %}
{% load l10n %}
{% block content %}
    <div class="container">
        <div style="margin-bottom: 20px">
            <a href="{% url 'cities:create' %}" class="btn btn-default block">Create</a></div>
        <ul class="block">
            {% for city in cities %}
                <li><a href="{% url 'cities:detail' city.id %}">City name: {{ city.name }}</a></li>
                <li><a href="{% url 'cities:detail' city.id %}">City latitude: {{ city.latitude }}</a></li>
                <li><a href="{% url 'cities:detail' city.id %}">City longitude: {{ city.longitude }}</a></li>
            {% endfor %}
            <p>Center:</p>
            <p>Latitude: {{ center.avg_lat }}</p>
            <p>Longitude: {{ center.avg_long }}</p>
        </ul>
        <div class='row'>

            <div class='col-sm-12'>
                <h3>My Google Maps Demo</h3>
                <button id="add-event-button" type="button" class="btn btn-success">
                    <span class="glyphicon glyphicon-plus-sign"></span> Add Event
                </button>
                <button id="clear-route" type="button" class="btn btn-danger">
                    <span class="glyphicon glyphicon-remove"></span> Clear path
                </button>

                <div id='map' class="gmap"></div>
            </div>
        </div>
    </div>
    <script>
        var locations = [
            {% for city in cities %}
                {
                    lat: {{ city.latitude|unlocalize }},
                    lng: {{ city.longitude|unlocalize }},
                    name: "{{ city.name }}",
{#                    address:"{{ biz.location.display_address.0 }} {{ biz.location.display_address.1 }}"#}
                },
            {% endfor %}
        ];
        var map;
        var all_blockposts = [];
        var marker_count = 0;
        var drawn_markers = [];
        var pos, pos2;
        var route;
        var markers;
        var infoWindow;
        var directionsDisplay;
        var directionsService;
        var drawingManager;

        function initMap() {
            // center of map
            var center = {lat: {{ center.avg_lat|unlocalize }}, lng: {{ center.avg_long|unlocalize }}};

            // map initialization
            var map = new google.maps.Map(document.getElementById('map'), {
                zoom: 14, // 0 to 18
                center: center,
                mapTypeId: 'roadmap',
            });
            
            // options to build routes
            directionsDisplay = new google.maps.DirectionsRenderer();
            directionsService = new google.maps.DirectionsService();

            // init draw manager to place markers on map
            drawingManager = new google.maps.drawing.DrawingManager({
                drawingMode: google.maps.drawing.OverlayType.MARKER,
                drawingControl: true,
                drawingControlOptions: {
                    position: google.maps.ControlPosition.TOP_CENTER,
                    drawingModes: ['marker']
                },
                markerOptions: {
                    icon: 'http://maps.google.com/mapfiles/ms/icons/blue.png'
                }
            });

            // add drawing tools to map
            drawingManager.setMap(map);

            // listener when we place marker on map (drawingManager)
            google.maps.event.addListener(drawingManager, 'markercomplete', function(marker) {
                marker_count += 1;
                if (marker_count == 1) {
                    // get first marker
                    pos2 = {lat: marker.position.lat(), lng: marker.position.lng()};
                    drawn_markers.push(marker)
                }
                if (marker_count == 2)
                {
                    // get second marker and draw route between them
                    pos = {lat: marker.position.lat(), lng: marker.position.lng()};
                    drawn_markers.push(marker);
                    plotRoute(pos, pos2, map);
                    directionsDisplay.setMap(map);
                }
                if (marker_count >= 2)
                {
                    // when we draw route - disable drawing mode, clear marker_count and remove drawn markers
                    drawingManager.setDrawingMode(null);
                    marker_count = 0;
                    while(drawn_markers.length)
                    {
                        drawn_markers.pop().setMap(null);
                    }

                }
            });

            infoWindow = new google.maps.InfoWindow();

            // function for creation markers and adding them to map
            // function createMaker(latlng, name, address){
            function createMaker(latlng, name){
                // var html = "<b>" + name + "</b><br/>" + address;
                var html = "<b>" + name + "</b>";
                var marker = new google.maps.Marker({
                    position: latlng,
                    map: map,
                    // animation: google.maps.Animation.BOUNCE, // manually
                    // icon: "pinkball.png"
                });
                all_blockposts.push(marker) // add marker to massive
                google.maps.event.addListener(marker, 'click', function(){
                    infoWindow.setContent(html);
                    infoWindow.open(map, marker);
                    // Zoom to 17 when clicking on marker and set center with marker's coords
                    // map.setZoom(17);
                    // map.setCenter(marker.getPosition());
                    // timeout for map back
                    // window.setTimeout(function() {map.setZoom(pos);},3000);
                })
            }

            // iterate loop with data for markers
            if (locations.length > 0) {
                for(var i = 0; i < locations.length; i++) {
                    var obj = locations[i];
                    var latlng = {lat: obj.lat, lng: obj.lng};
                    createMaker(latlng, obj.name);
                    // createMaker(latlng, obj.name, obj.address)
                }
            }
        }

        //CREATES A ROUT
        // after calling the function, add: directionsDisplay.setMap(map)
        function plotRoute(pos, pos2, map) {
            var request = {
                origin: pos2,
                destination: pos,
                travelMode: 'DRIVING'
            };
            directionsService.route(request, function(result, status) {
                if (status === 'OK') {
                    directionsDisplay.setDirections(result); // display route on map
                    console.log(result.routes[0].overview_polyline)
                    // get pathes list to create Polyline object
                    var cascadiaFault = new google.maps.Polyline({
                        path: google.maps.geometry.encoding.decodePath(result.routes[0].overview_polyline)
                    });
                    // cascadiaFault.setMap(map);
                    
                    // check if blockpost on map
                    for (var i = 0; i < all_blockposts.length; i++){
                        if (google.maps.geometry.poly.isLocationOnEdge(all_blockposts[i].position, cascadiaFault, 0.001)) {
                            alert(i+1);
                        }
                        else {
                            // alert("Ok")
                        }
                    }
                    
                }
            });
        }

        // START DRAW MARKERS
        document.getElementById('add-event-button').onclick = function() {
            drawingManager.setDrawingMode(google.maps.drawing.OverlayType.MARKER);
        };

        // CLEAR ALL ROUTES
        document.getElementById('clear-route').onclick = function() {
            directionsDisplay.setMap(null);
            directionsDisplay = null;
            directionsDisplay = new google.maps.DirectionsRenderer();
            directionsDisplay.setMap(map); 
            drawingManager.setDrawingMode(google.maps.drawing.OverlayType.MARKER);
        };

    </script>

{% endblock content %}

{% block script %}
    <script async defer src="https://maps.googleapis.com/maps/api/js?key=AIzaSyAqOazqPcP8E-_s-Vp7MRbP3UMUgS2xfQw&callback=initMap&libraries=drawing,geometry"></script>
{% endblock script %}